fade: 5
fade_in_seconds: 5
fade_out_seconds: 5
filesystem_default_fade_in: false
filesystem_default_fade_out: false
streams_default_fade_in: false
streams_default_fade_out: false
font:
  size: 12
library_tabs:
supported_extensions:
  - "mp3"
  - "ogg"
  - "opus"
  - "mp4"
  - "webm"
  - "aac"
  - "mkv"
  - "mpg"
  - "mpeg"
  - "m3u"
  - "m3u8"
  - "pls"
  - "xspf"
  - "mov"
  - "wav"
  - "flac"
  - "m4a"
  - "avi"
  - "flv"
greenwich_time_signal_enabled: false
greenwich_time_signal_path: "/home/zital/Gts_(bbc)_pips.ogg"
